export * from './Logo'
export * from './HeartBpm'
export * from './RespiratoryRate'
export * from './Temperature'
export * from './InsuranceIcon'
export * from './BirthIcon'
export * from './PhoneIcon'
export * from './FemaleIcon'
export * from './InsuranceIcon'

